#!/usr/bin/env python2.6
# -*- Mode: python -*-

import sys
import tempfile

import pyenv


def worker():
    all_actions = pyenv.Actions.get_all_actions()

    try:
        pyenv.options.TopLevelOptions.parse(sys.argv[1:], all_actions, pyenv.shell_mapper.keys())
    except pyenv.OptionParsingError as e:
        # no shell at this point, so we've already dumped everything to stderr.  just reraise.
        raise

    # set up module database.
    mdb = pyenv.ModuleDatabase()

    # figure out which shell...
    shell = pyenv.shell_mapper[pyenv.options.TopLevelOptions.shell](pyenv.options.TopLevelOptions)

    env = pyenv.Environment(shell, mdb)

    action_requested = pyenv.options.TopLevelOptions.action
    action_arguments = pyenv.options.TopLevelOptions.action_options

    assert(action_requested in all_actions)
    action_processor = all_actions[action_requested]
    try:
        action_processor(action_requested, action_arguments, env, shell, mdb)
    except pyenv.OptionParsingError as e:
        # we have a shell, so just clean up normally.
        pass

    env.shutdown()

    wlog = pyenv.WarningLog.get_logger()

    for log_msg in wlog.get_log():
        shell.write("%s" % log_msg)

    shell_state = shell.dump_state()

    if (pyenv.options.TopLevelOptions.dump or pyenv.options.TopLevelOptions.dry_run):
        sys.stderr.write("\n".join(shell_state) + "\n")

    if (pyenv.options.TopLevelOptions.dry_run):
        raise pyenv.OptionParsingError("not really an error, we just don't want to execute "
                                       "a dry run")

    return shell_state



def main():
    name = None
    try:
        shell_state = worker()

        # write this to a temp file.
        tfh = tempfile.NamedTemporaryFile(delete=False)
        name = tfh.name

        tfh.write("\n".join(shell_state) + "\n")

        tfh.close()
    except pyenv.OptionParsingError as e:
        # ignore the error if it gets this far up.
        sys.exit(1)
    finally:
        # write the name of the temp file to the shell.
        if (name is not None):
            sys.stdout.write("%s\n" % name)

if __name__ == "__main__":
    main()
